apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.postgres.name }}
    port: {{ .Values.postgres.service.port }}
    protocol: TCP
    targetPort: {{ .Values.postgres.service.port }}
  selector:
    app: {{ .Values.postgres.name }}
---
